// app/layout.tsx
import type { Metadata } from "next";
import { Figtree, Geist, Geist_Mono } from "next/font/google";

import LunionNav from "@/components/common/nav/LunionNav";
import { Footer } from "@/components/common/footer";
import LunionLabFooter from "@/components/common/Footer copy";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DefaultLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${figtree.variable} antialiased`}
        suppressHydrationWarning
      >
        <LunionNav />
        {/* Tout le contenu dynamique doit être Client Component */}
        {children}
        <LunionLabFooter />
      </body>
    </html>
  );
}
